uses:
  - name: feed-management
    version: 1.0.0
  - name: follow-management
    version: 0.21.2
  - name: feed-like-management
    version: 0.5.1
  - name: feed-report-management
    version: 0.1.8
    project: sns

packages:
  vapis/feed-report-management:
    name: feed-report-management
    version: 0.1.8
    access: private
    shortDescription: "사용자가 부적절하다고 판단되는 피드를 신고할 수 있는 기능을 관리한다. 신고된 피드는 리뷰 프로세스를 거쳐 조치된다."
    longDescription: |
      # Feed Report Management
      
      사용자가 부적절하다고 판단되는 피드를 신고할 수 있는 기능을 관리한다. 신고된 피드는 리뷰 프로세스를 거쳐 조치된다.
      
      ## Supported features
        - `POST /register-feed-report`: 피드 신고 등록
        - `GET /list-reported-feeds`: 신고된 피드 목록 조회
        - `PUT /update-report-status`: 신고 처리 상태 업데이트
    dependencies:
      feed-management: "1.0.0"
